server:
  port: 8088

person:
    lastName: zero
    age: 18
    boss: false
    birth: 2017/12/12
    maps: {k1: v1,k2: v2}
    lists:
      - lisi
      - zhaoliu
    dog:
      name: Cat
      age: 2